[package]
name = "binance_ws_listener"
version = "0.1.0"
edition = "2018"

[dependencies]
tokio = { version = "1", features = ["full"] }
native-tls = "0.2"
tungstenite = { version = "0.17.3", features = ["native-tls"] }
futures = "0.3"
url = "2"

